"use client";
import { DndContext, DragEndEvent, DragOverlay, PointerSensor, useDraggable, useDroppable, useSensor, useSensors } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Deal = { id: string; name: string; amount: number | null; expectedCloseDate: string | null; ownerName: string; companyName: string | null; stageId: string };
type Stage = { id: string; name: string; stageType: "OPEN" | "WON" | "LOST"; probability: number; deals: Deal[] };
export function KanbanBoard({ stages }: { stages: Stage[] }) { const router = useRouter(); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } })); const [active, setActive] = useState<Deal | null>(null); const [error, setError] = useState(""); async function dragEnd(event: DragEndEvent) { setActive(null); const deal = stages.flatMap((s) => s.deals).find((d) => d.id === event.active.id); const stage = stages.find((s) => s.id === event.over?.id); if (!deal || !stage || deal.stageId === stage.id) return; let lostReason: string | null = null; if (stage.stageType === "LOST") { lostReason = window.prompt("失注理由を入力してください。"); if (!lostReason) return; } const response = await fetch(`/api/deals/${deal.id}/stage`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ stageId: stage.id, lostReason }) }); const result = await response.json(); if (!response.ok) return setError(result.message ?? "ステージを変更できませんでした。"); setError(""); router.refresh(); }
  return <DndContext sensors={sensors} onDragStart={(event) => setActive(stages.flatMap((s) => s.deals).find((d) => d.id === event.active.id) ?? null)} onDragEnd={dragEnd} onDragCancel={() => setActive(null)}>{error ? <p className="mb-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}<div className="flex gap-4 overflow-x-auto pb-5">{stages.map((stage) => <StageColumn key={stage.id} stage={stage} />)}</div><DragOverlay>{active ? <DealCard deal={active} overlay /> : null}</DragOverlay></DndContext>; }
function StageColumn({ stage }: { stage: Stage }) { const { setNodeRef, isOver } = useDroppable({ id: stage.id }); const total = stage.deals.reduce((sum, d) => sum + (d.amount ?? 0), 0); return <section ref={setNodeRef} className={`w-[300px] shrink-0 rounded-2xl border p-3 transition ${isOver ? "border-brand-500 bg-brand-50" : "border-line bg-[#eef1ed]"}`}><div className="mb-3 px-1"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">{stage.name}</h2><span className="rounded-full bg-white px-2 py-0.5 text-xs font-bold text-slate-500">{stage.deals.length}</span></div><p className="mt-1 text-xs text-slate-500">{total.toLocaleString("ja-JP")}円 ・ 確度{stage.probability}%</p></div><div className="min-h-24 space-y-3">{stage.deals.map((deal) => <DraggableCard key={deal.id} deal={deal} />)}</div></section>; }
function DraggableCard({ deal }: { deal: Deal }) { const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: deal.id }); return <div ref={setNodeRef} style={{ transform: CSS.Translate.toString(transform) }} {...listeners} {...attributes} className={isDragging ? "opacity-30" : "cursor-grab active:cursor-grabbing"}><DealCard deal={deal} /></div>; }
function DealCard({ deal, overlay = false }: { deal: Deal; overlay?: boolean }) { return <article className={`rounded-xl border border-line bg-white p-4 ${overlay ? "w-[285px] rotate-2 shadow-xl" : "shadow-sm"}`}><Link href={`/deals/${deal.id}`} onClick={(e) => e.stopPropagation()} className="text-sm font-bold hover:text-brand-700">{deal.name}</Link><p className="mt-2 text-xs text-slate-500">{deal.companyName ?? "会社未設定"}</p><p className="mt-4 text-lg font-bold">{deal.amount ? `${deal.amount.toLocaleString("ja-JP")}円` : "金額未設定"}</p><div className="mt-3 flex items-end justify-between text-xs text-slate-400"><span>{deal.ownerName}</span><span>{deal.expectedCloseDate ? new Intl.DateTimeFormat("ja-JP", { month: "short", day: "numeric" }).format(new Date(deal.expectedCloseDate)) : "予定日なし"}</span></div></article>; }
