import { NextResponse } from "next/server";
import { apiError } from "@/lib/api";
import { getAuthContext } from "@/lib/auth";
import { Permission, requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { pipelineStageSchema } from "@/lib/validation";
type Params = { params: Promise<{ id: string }> };
export async function PATCH(request: Request, { params }: Params) { try { const context = await getAuthContext(); if (!context) return NextResponse.json({ message: "ログインが必要です。" }, { status: 401 }); requirePermission(context.membership.role, Permission.MANAGE_PIPELINES); const { id } = await params; const current = await prisma.pipelineStage.findFirst({ where: { id, organizationId: context.organization.id } }); if (!current) return NextResponse.json({ message: "ステージが見つかりません。" }, { status: 404 }); const input = pipelineStageSchema.parse(await request.json()); const item = await prisma.$transaction(async (tx) => { if (input.sortOrder !== current.sortOrder) { const occupied = await tx.pipelineStage.findUnique({ where: { pipelineId_sortOrder: { pipelineId: current.pipelineId, sortOrder: input.sortOrder } } }); if (occupied && occupied.id !== current.id) { const temporaryOrder = 1000000 + current.sortOrder; await tx.pipelineStage.update({ where: { id: current.id }, data: { sortOrder: temporaryOrder } }); await tx.pipelineStage.update({ where: { id: occupied.id }, data: { sortOrder: current.sortOrder } }); } } return tx.pipelineStage.update({ where: { id }, data: input }); }); return NextResponse.json({ item }); } catch (error) { return apiError(error); } }
export async function DELETE(_: Request, { params }: Params) { try { const context = await getAuthContext(); if (!context) return NextResponse.json({ message: "ログインが必要です。" }, { status: 401 }); requirePermission(context.membership.role, Permission.MANAGE_PIPELINES); const { id } = await params; const stage = await prisma.pipelineStage.findFirst({ where: { id, organizationId: context.organization.id }, include: { _count: { select: { deals: true } } } }); if (!stage) return NextResponse.json({ message: "ステージが見つかりません。" }, { status: 404 }); if (stage._count.deals) return NextResponse.json({ message: "商談が存在するステージは削除できません。" }, { status: 409 }); await prisma.pipelineStage.delete({ where: { id } }); return NextResponse.json({ ok: true }); } catch (error) { return apiError(error); } }
